// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rules

import (
	"github.com/IgorSteps/dblinter/internal/diagnostics"
	"github.com/IgorSteps/dblinter/internal/rules"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRule creates a new instance of MockRule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRule {
	mock := &MockRule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRule is an autogenerated mock type for the Rule type
type MockRule struct {
	mock.Mock
}

type MockRule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRule) EXPECT() *MockRule_Expecter {
	return &MockRule_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockRule
func (_mock *MockRule) Check(calls []rules.CallSite) ([]diagnostics.Issue, error) {
	ret := _mock.Called(calls)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 []diagnostics.Issue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]rules.CallSite) ([]diagnostics.Issue, error)); ok {
		return returnFunc(calls)
	}
	if returnFunc, ok := ret.Get(0).(func([]rules.CallSite) []diagnostics.Issue); ok {
		r0 = returnFunc(calls)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]diagnostics.Issue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]rules.CallSite) error); ok {
		r1 = returnFunc(calls)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRule_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockRule_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - calls []rules.CallSite
func (_e *MockRule_Expecter) Check(calls interface{}) *MockRule_Check_Call {
	return &MockRule_Check_Call{Call: _e.mock.On("Check", calls)}
}

func (_c *MockRule_Check_Call) Run(run func(calls []rules.CallSite)) *MockRule_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []rules.CallSite
		if args[0] != nil {
			arg0 = args[0].([]rules.CallSite)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRule_Check_Call) Return(issues []diagnostics.Issue, err error) *MockRule_Check_Call {
	_c.Call.Return(issues, err)
	return _c
}

func (_c *MockRule_Check_Call) RunAndReturn(run func(calls []rules.CallSite) ([]diagnostics.Issue, error)) *MockRule_Check_Call {
	_c.Call.Return(run)
	return _c
}
